export const REVIEW_LIST_MY_REQUEST = 'REVIEW_LIST_MY_REQUEST';
export const REVIEW_LIST_MY_SUCCESS = 'REVIEW_LIST_MY_SUCCESS';
export const REVIEW_LIST_MY_FAIL = 'REVIEW_LIST_MY_FAIL';
export const REVIEW_LIST_MY_RESET = 'REVIEW_LIST_MY_RESET';

export const REVIEW_LIST_REQUEST = 'REVIEW_LIST_REQUEST';
export const REVIEW_LIST_SUCCESS = 'REVIEW_LIST_SUCCESS';
export const REVIEW_LIST_FAIL = 'REVIEW_LIST_FAIL';
export const REVIEW_LIST_RESET = 'REVIEW_LIST_RESET';

export const REVIEW_UPDATE_MY_REQUEST = 'REVIEW_UPDATE_MY_REQUEST';
export const REVIEW_UPDATE_MY_SUCCESS = 'REVIEW_UPDATE_MY_SUCCESS';
export const REVIEW_UPDATE_MY_FAIL = 'REVIEW_UPDATE_MY_FAIL';
export const REVIEW_UPDATE_MY_RESET = 'REVIEW_UPDATE_MY_RESET';

export const REVIEW_DELETE_MY_REQUEST = 'REVIEW_DELETE_MY_REQUEST';
export const REVIEW_DELETE_MY_SUCCESS = 'REVIEW_DELETE_MY_SUCCESS';
export const REVIEW_DELETE_MY_FAIL = 'REVIEW_DELETE_MY_FAIL';
export const REVIEW_DELETE_MY_RESET = 'REVIEW_DELETE_MY_RESET';

export const REVIEW_DETAILS_REQUEST = 'REVIEW_DETAILS_REQUEST';
export const REVIEW_DETAILS_SUCCESS = 'REVIEW_DETAILS_SUCCESS';
export const REVIEW_DETAILS_FAIL = 'REVIEW_DETAILS_FAIL';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAIL = 'REVIEW_DELETE_FAIL';
export const REVIEW_DELETE_RESET = 'REVIEW_DELETE_RESET';
